monitor/ad/urls.py
#!/usr/bin/env python
#coding=utf-8
"""day11 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.contrib import admin
from .views import *

from django.urls import path

import sys

#dir_path = sys.path[1]
sys.path.append('G:\python\eclipse\day11\day11')



'''
urlpatterns = [
    path(r'^admin/', admin.site.urls),

    path(r'^index/$', index),
    path(r'^login/$', login),
    path(r'^list/(\d*)/$', list),
    path(r'^list2/(?P<name>\d*)/$', list2),
    path(r'^list2/(?P<alex>\d*)/$', list2,{'id':222}),
    path(r'^web/', include('web.url')),
    path(r'^ad/', include('ad.url'))
    
]
'''
urlpatterns = [
    #path(r'admin/', admin.site.urls),
    path(r'login/', login),
    path(r'assetupdate/', AssetUpdate),
    path(r'userupdate/', UserUpdate),
    path(r'assetlist/', AssetList),
    path(r'assetlist/<int:page_num>/', AssetList),
    path(r'register/', Register),
    path(r'userlist/', UserList),
    path(r'userlist/<int:page_num>/', UserList),
    path(r'auth/', auth),
    path(r'auth2/', auth2),
    path(r'monitor/monitor/', server_monitor_monitor),
    path(r'monitor/warning/', server_monitor_warning),
    path(r'monitor/warning/<int:page_num>/', server_monitor_warning),
    path(r'monitor/warningupdate/', server_monitor_warning_update),
    path(r'monitor/warningupdate/<int:page_num>/', server_monitor_warning_update),
    path(r'monitor/hostgroup/', server_monitor_hostgroup),
    path(r'monitor/hostgroup/<int:page_num>/', server_monitor_hostgroup),
    path(r'monitor1/', server_monitor_host),
    path(r'monitor1/<int:page_num>/', server_monitor_host),
    path(r'monitor/templates/', server_monitor_templates),
    path(r'monitor/templates/<int:page_num>/', server_monitor_templates),
    path(r'monitor/triggers/', server_monitor_triggers),
    path(r'monitor/triggers/<int:page_num>/', server_monitor_triggers),
    path(r'monitor/message/<int:u_id>/', server_monitor_message),
    path(r'monitor/<name>/', server_monitor),
    path(r'exit/', ad_exit),
    path(r'quit/', ad_exit),
]

monitor/monitor/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ad/', include('ad.urls')),
]

monitor/ad/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import django
# Create your models here.


class UserInfo(models.Model):
    user_type_choice = (
        (int(0), u'普通管理员'),
        (int(1), u'超级管理员'),
    )
    user_type = models.IntegerField(choices=user_type_choice)
    name = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=256)
    salt = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salt', null=True)
    # hash = hashlib.md5()
    # hash.update(password)
    # password = hash.hexdigest()
    email = models.EmailField()
    memo = models.TextField(null=True)
    # typeId = models.ForeignKey('UserType')
    atime = models.DateTimeField(auto_now=True)
    ctime = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


class Salt(models.Model):
    value = models.BinaryField(max_length=256)


class UserGroup(models.Model):
    Name = models.CharField(max_length=50)


class Asset(models.Model):
    hostname = models.CharField(max_length=30, unique=True)
    ip = models.GenericIPAddressField(unique=True)
    user_group = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserGroup', default=2)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    hostgroup = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HostGroup', default=1)


# monitor models
# 下面是监控相关model


class HostGroup(models.Model):
    name = models.CharField(max_length=32, unique=True)
    # templates = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Templates')
    templates = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Templates')
    memo = models.TextField(u"备注", blank=True, null=True)

    def __unicode__(self):
        return self.name


class Templates(models.Model):
    name = models.CharField(max_length=32, unique=True)
    # triggers = models.ManyToManyField('Triggers', verbose_name=u"触发器列表", blank=True)
    # triggers_choice = (
    # (int(0), u'普通管理员'),
    # (int(1), u'超级管理员'),
    # )
    triggers = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Triggers')
    memo = models.TextField(max_length=64)


class Triggers(models.Model):
    name = models.CharField(max_length=32, unique=True)
    # triggers_index = models.IntegerField()
    # rule = models.IntegerField()
    memo = models.TextField(u"备注", blank=True, null=True)

    def __unicode__(self):
        return self.name


# class TriggersIndex(models.Model):
#     name = models.CharField(max_length=32, unique=True)
#     templates = models.IntegerField()


# class Rule(models.Model):
#     name = models.CharField(max_length=32)
#     rule_index = models.IntegerField()
#     memo = models.TextField(max_length=64)


class RuleIndex(models.Model):
    name_choice = (
        (int(0), u'无响应'),
        (int(1), u'CPU使用率'),
        (int(2), u'内存使用率'),
        (int(3), u'磁盘Inode'),
        (int(4), u'磁盘空间'),
        (int(5), u'磁盘IOPS'),
        (int(6), u'发送流量'),
        (int(7), u'连接数'),
        (int(8), u'接收流量'),
        (int(9), u'端口检查'),
    )
    name = models.IntegerField(choices=name_choice)
    triggers = models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Triggers')
    time_choice = (
        (int(1), u'1分钟'),
    )
    time = models.IntegerField(choices=time_choice)
    triggers_times_choice = (
        (int(0), u'连续1次'),
        (int(1), u'连续3次'),
        (int(2), u'连续5次'),
        (int(3), u'连续10次'),
        (int(4), u'连续15次'),
        (int(5), u'连续30次'),
    )
    triggers_times = models.IntegerField(choices=triggers_times_choice)
    triggers_diff_choice = (
        (int(0), u'>='),
        (int(1), u'>'),
        (int(2), u'<='),
        (int(3), u'<'),
        (int(4), u'='),
        (int(5), u'!='),
    )
    triggers_diff = models.IntegerField(choices=triggers_diff_choice)
    triggers_value = models.IntegerField()
    warning = models.IntegerField(default=0)
    switch = models.BooleanField(default=True)


class RuleResult(models.Model):
    time = models.DateTimeField()
    data = models.TextField()
    host = models.CharField(max_length=30)

monitor/ad/forms.py
#!/usr/bin/env python
# coding=utf-8

from django import forms
from . import models

'''
class RegisterForm(forms.Form):
    name = forms.CharField()
    password = forms.CharField()
    email = forms.EmailField(required=True,error_messages={'invalid':'邮箱格式不合法'})
    memo = forms.CharField()
    typeId = forms.ChoiceField()
'''


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = models.UserInfo
        fields = ('name', 'password', 'email', 'memo', 'user_type')
        widgets = {
            'password': forms.PasswordInput(attrs={'type': 'password'})
        }


class AssetListForm(forms.Form):
    usergroup_choice = (
        (int(1), u'运维组'),
        (int(2), u'开发组'),
        (int(3), u'DBA组'),
    )
    hostname = forms.CharField(max_length=30)
    ip = forms.GenericIPAddressField()
    user_group = forms.IntegerField(widget=forms.widgets.Select(choices=usergroup_choice))


class RuleIndexForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = models.RuleIndex
        fields = ('name', 'triggers', 'time', 'triggers_times',
                  'triggers_diff', 'triggers_value', 'switch')


class TemplatesForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = models.Templates
        fields = ('name', 'triggers', 'memo')


'''
class AssetListForm(forms.ModelForm):
    class Meta:
        usergroup_choice = (
            (int(1),u'运维组'),
            (int(2),u'开发组'),
            (int(3),u'DBA组'),
        )
        model = models.Asset
        fields = ('hostname','ip',)
        #widgets = {
        #    'user_group' : forms.Select(choices=usergroup_choice),
        #}
        widgets = {
            'user_group':forms.widgets.Select(choices=usergroup_choice),
        }
        #help_texts = {'user_group':(u'运维组/开发组/DBA组'),}
'''


# class RegisterForm2(forms.Form):
#     user_type_choice = (
#         (1, u'普通管理员'),
#         (2, u'超级管理员'),
#         )
#     user_type = forms.IntegerField(widget=forms.widgets.Select(choices=user_type_choice,
#                                                                attrs={'class': "form-control"}))


'''
class RegisterForm2(forms.ModelForm):
    class Meta:
        model = models.UserInfo
        fields = ('typeId',)
'''
'''
        fields = ('name','password','email','memo','typeId')
'''

monitor/templates/hostgroup.html
{% extends "master/layout.html" %}
{% load oldboy %}
{% block content %}

<h2 style='position:relative;left:3%'>主机组</h2>
	<form action='/ad/monitor/hostgroup/' method='POST'>{% csrf_token %}
		<table style='position:relative;left:8%;top:10px;bottom:50px' border='1'>
			<th>
				<td>主机组</td>
				<td>模板</td>
				<td>描述</td>
				<td>主机</td>
				<td></td>
			</th>		
			{% for item in data%}
			
			
			<tr name="RuleIndextable">
				<td>{{item.id}}</td>
				<td >{{item.name}}</td>
				<td >{{item.templates.name}}</td>
				<td>{{item.memo}}</td>
				<td>{% get_hosts host_list item.id %}</td>
				<td style='border-style:none'><input id={{item.id}} type="button" value="保存" onclick="javascript:submitdata(this)"/></td>
			</tr>		
			{% endfor %}
			
			<!-- <tr name="assettable">
				<td>{{item.id}}</td>
				<td id="1000name">{% mymethod item.id %}</td>
				<td ><input name="hostname"/></td>
				<td ><input name="ip"/></td>
				<td>{{item.create_date|date:"Y-m-d H:i:s"}}</td>
				<td>{{item.update_date|date:"Y-m-d H:i:s"}}</td>
				<td ><select name="groupid">
					<option value=2>运维组</option>
					<option value=1>管理组</option>
				</select></td>
				<td style='border-style:none'><input type='submit' value='新增'/></td>
			</tr> -->
			
			<tr name="new_hostgroup">
				<td></td>
				<td><input name="hostgroup_name" style="height:16px"/></td>
				<td><select name="hostgroup_templates" style="height:22px">
					{% for i in form2 %}
					<option  value="{{i.id}}">{{i.name}}</option>
					{% endfor  %}
				</select></td>
				<td><input name="hostgroup_memo" style="height:16px"/></td>
				<td></td>
				<td style='border-style:none'><input type='submit' value='新增'/></td>
			</tr>
		
		</table>
	</form>
	<form><table style='position:relative;left:22%;top:20px;bottom:50px' border="1px">
	<tr ><div >
			<td><a href="/ad/monitor/hostgroup/{{up_page}}/">上一页</a></td>
			<td>&nbsp;<span>{{page_num}}</span>&nbsp;</td>
			<td><a href="/ad/monitor/hostgroup/{{down_page}}/">下一页</a></td>
		</div></tr>
	</table></form>
<img style="position:fixed;right:150px;bottom:134px;height:34px;width:34px" src="/static/img/sanjiaoxing2.png" />
<button id="backtop" style="position:fixed;right:150px;bottom:100px;height:34px;width:34px">Top</button>
<script type="text/javascript" src="/static/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
var jishi=document.getElementsByClassName("td-1");
			//遍历数组，给每个td添加点击事件
			for(var j=0;j<jishi.length;j++){
				jishi[j].onclick=function(){
				//首先要创造个输入框
				var shuru=document.createElement("input");
				//给输入框添加类型，因为输入框有很多的类型
				shuru.type="text";
				//输入框的内容是本身就有的，获取它的内容，用指针来代替
				shuru.value=this.innerText;
				var shuru1=shuru.value
				//把td的内容清空，然后把新建的节点加给它
				this.innerHTML="";
				this.appendChild(shuru);
				shuru.onblur=function(){
					shuru.parentNode.innerHTML=shuru.value;
				}
				shuru.focus();
				}
			}
backtop.onclick = function(){
	document.body.scrollTop = document.documentElement.scrollTop = 0;
}
function submitdata(obj){
	//alert('数据提交成功');
	var subhm=obj.parentNode.parentNode.childNodes[5].innerHTML;
	var subip=obj.parentNode.parentNode.childNodes[7].innerHTML;
	$.ajax({
		url:"/ad/assetupdate/",
		data:{id:obj.id,hostname:subhm,ip:subip,csrfmiddlewaretoken: '{{ csrf_token }}'},
		type:'POST',
		success:function(data){
			//console.log('success');
			alert(data);
		},
		error:function(data){
			console.log(data);
		},
	});
}
</script>

{% endblock %}

monitor/templates/hostinfo.html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title></title>
</head>
<body>
<table>
	<tr><th>vcc_pc</th></tr>
	<tr>
		<td>{{vcc_pc.cpupercent}}</td>
		<td>{{vcc_pc.mempercent}}</td>
		<td>{{vcc_pc.diskpercent}}</td>
		<td>{{vcc_pc.inode}}</td>
		<td>{{vcc_pc.disksize}}</td>
		<td>{{vcc_pc.readcount}}</td>
		<td>{{vcc_pc.writecount}}</td>
		<td>{{vcc_pc.sentbyte}}</td>
		<td>{{vcc_pc.recvbyte}}</td>
	</tr>
</table>
</body>
</html>

monitor/templates/login2.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
    <title>华熙现场监控-欢迎登录</title>
	<!-- <link rel="icon" href="favicon.ico"/> -->
    <link rel="icon" href="/static/img/favicon.ico"/>
    <link type="text/css" rel="stylesheet"
          href="/static/css/login.css"/>
	<script src="http://cdn.bootcss.com/blueimp-md5/1.1.0/js/md5.js"></script>   
	<script src="http://cdn.bootcss.com/blueimp-md5/1.1.0/js/md5.min.js"></script>
	<script>
	function checkInput() {
    var password = document.getElementById('password');
    <!-- var password_md5 = document.getElementById('password_md5'); -->

    // set password
    password.value =  md5(password.value);
    return true;
	}
	</script>
	</head>

<body>

<div><a href='/ad/login/'><img src="/static/img/page_logo.gif" alt="华熙现场官网" /></a></div>
<div  class="micro-title1"><img src='/static/img/pic6.jpg' alt='二维码' /></div>
<div class='login-box1'>
	<a href='http://wks.bloomagelive.com/'><img style="width:660px" src='/static/img/AI.png' alt='aryn'  /></a>
</div>
<div class='login-box2'>
		<a href="/ad/assetlist/">{% csrf_token %}
		<div><input name="assetlist" type='submit' value="当前用户: {{user}}" style='position:relative;left:30px' class='th-submit3'/></div>
		</a>
		<a href="/ad/exit/">{% csrf_token %}
		<div><input name="signout" type="submit" value="登出" style='position:relative;left:30px;margin-top:15px' class='th-submit3'/></div>
		</a>
</div>

<div class='bottom-sty' style="position:fixed;left:40%">

	<h6>©华熙现场科技有限公司    <span style="color:black">版权所有</span> <a href="http://www.miitbeian.gov.cn"><span style="color:black">京ICP备16047864号-1</span></a></h6>

</div>



</body>

</html>

monitor/templates/message.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
    <title>华熙现场-监控系统</title>
	<!-- <link rel="icon" href="favicon.ico"/> -->
    <link rel="icon" href="/static/img/favicon.ico"/>
    <link type="text/css" rel="stylesheet"
          href="/static/css/login.css"/>
	<script src="http://cdn.bootcss.com/blueimp-md5/1.1.0/js/md5.js"></script>   
	<script src="http://cdn.bootcss.com/blueimp-md5/1.1.0/js/md5.min.js"></script>
	<script>
	function checkInput() {
    var password = document.getElementById('password');
    <!-- var password_md5 = document.getElementById('password_md5'); -->

    // set password
    password.value =  md5(password.value);
    return true;
	}
	</script>
</head>
<body>

<div >
<ul>
	<li><a href='/ad/userlist/'>用户管理</a></li>
	<li><a href='/ad/assetlist/'>资产管理</a></li>
	<li><a href='/ad/monitor1/'>主机监控</a><ul>
		<li><a href='/ad/monitor/hostgroup/'>主机组</a></li>
		<li><a href='/ad/monitor/templates/'>主机模板</a></li>
		<li><a href='/ad/monitor/triggers/'>主机触发器</a></li>
		<li><a href='/ad/monitor/warning/'>告警规则</a></li>
	</ul></li>
</ul>
</div>
{% load oldboy %}


<h2 style='position:relative;left:3%'>主机数据</h2>
	<form action='/ad/monitor/warning/' method='POST'>{% csrf_token %}
		<table style='position:relative;left:8%;top:10px;bottom:50px' border='1'>
			
			<th>
				<td>主机组</td>
				<td>模板</td>
				
				<td>主机</td>
				
			</th>		
			
			
			
			<tr name="message">
				<td>{{host_group.id}}</td>
				<td >{{host_group.name}}</td>
				<td>{{host_group.templates.name}}</td>
				<td>{{host_list}}</td>
				<td>{{data}}</td>
				
			</tr>		
			
			
			<!-- <tr name="assettable">
				<td>{{item.id}}</td>
				<td id="1000name">{% mymethod item.id %}</td>
				<td ><input name="hostname"/></td>
				<td ><input name="ip"/></td>
				<td>{{item.create_date|date:"Y-m-d H:i:s"}}</td>
				<td>{{item.update_date|date:"Y-m-d H:i:s"}}</td>
				<td ><select name="groupid">
					<option value=2>运维组</option>
					<option value=1>管理组</option>
				</select></td>
				<td style='border-style:none'><input type='submit' value='新增'/></td>
			</tr> -->
		
		</table>
	</form>


<img style="position:fixed;right:150px;bottom:134px;height:34px;width:34px" src="/static/img/sanjiaoxing2.png" />
<button id="backtop" style="position:fixed;right:150px;bottom:100px;height:34px;width:34px">Top</button>
<script type="text/javascript" src="/static/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
var jishi=document.getElementsByClassName("td-1");
			//遍历数组，给每个td添加点击事件
			for(var j=0;j<jishi.length;j++){
				jishi[j].onclick=function(){
				//首先要创造个输入框
				var shuru=document.createElement("input");
				//给输入框添加类型，因为输入框有很多的类型
				shuru.type="text";
				//输入框的内容是本身就有的，获取它的内容，用指针来代替
				shuru.value=this.innerText;
				var shuru1=shuru.value
				//把td的内容清空，然后把新建的节点加给它
				this.innerHTML="";
				this.appendChild(shuru);
				shuru.onblur=function(){
					shuru.parentNode.innerHTML=shuru.value;
				}
				shuru.focus();
				}
			}
backtop.onclick = function(){
	document.body.scrollTop = document.documentElement.scrollTop = 0;
}
function submitdata(obj){
	//alert('数据提交成功');
	var subhm=obj.parentNode.parentNode.childNodes[5].innerHTML;
	var subip=obj.parentNode.parentNode.childNodes[7].innerHTML;
	$.ajax({
		url:"/ad/assetupdate/",
		data:{id:obj.id,hostname:subhm,ip:subip,csrfmiddlewaretoken: '{{ csrf_token }}'},
		type:'POST',
		success:function(data){
			//console.log('success');
			alert(data);
		},
		error:function(data){
			console.log(data);
		},
	});
}
</script>

<div style="position:relative;min-height:50px">
<div style="margin-bottom:60px"></div>
<div style="absolute: fixed;  bottom: 0;height: 60px;margin-left:40%">

	<h5>©华熙现场科技有限公司    <span style="color:black">版权所有</span> <a href="http://www.miitbeian.gov.cn"><span style="color:black">京ICP备16047864号-1</span></a ></h5>

</div>
</div>

monitor/templates/monitor_monitor.html
{% csrf_token %}

monitor/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge"/>
    <title>华熙现场-监控系统</title>
	<!-- <link rel="icon" href="favicon.ico"/> -->
    <link rel="icon" href="/static/img/favicon.ico"/>
    <link type="text/css" rel="stylesheet"
          href="/static/css/login.css"/>
	<script src="http://cdn.bootcss.com/blueimp-md5/1.1.0/js/md5.js"></script>   
	<script src="http://cdn.bootcss.com/blueimp-md5/1.1.0/js/md5.min.js"></script>
	<script>
	function checkInput() {
    var password = document.getElementById('password');
    <!-- var password_md5 = document.getElementById('password_md5'); -->

    // set password
    password.value =  md5(password.value);
    return true;
	}
	</script>
</head>
<body>

<div >
<ul>
	<li><a href='/ad/userlist/'>用户管理</a></li>
	<li><a href='/ad/assetlist/'>资产管理</a></li>
	<li><a href='/ad/monitor1/'>主机监控</a><ul>
		<li><a href='/ad/monitor/hostgroup/'>主机组</a></li>
		<li><a href='/ad/monitor/templates/'>主机模板</a></li>
		<li><a href='/ad/monitor/triggers/'>主机触发器</a></li>
		<li><a href='/ad/monitor/warning/'>告警规则</a></li>
	</ul></li>
</ul>
</div>

<div>


<form style='position:fixed;left:18%;top:15%;background-color:rgba(0,0,0,0.1);width:500px;height:650px;border: 1px solid #3481cf;' action='/ad/register/' onsubmit="checkInput()" method='POST'>{% csrf_token %}
<h4 style='position:relative;left:35%;top:100px'>欢迎注册</h4>
	<!--   {{form.as_table}} -->
	<table style='position:relative;left:10%;top:100px' >
				<tr><th><label for="id_name">名称:</label></th><td><input type="text" name="name" id="id_name" required maxlength="30" /></td></tr>
<tr><th><label for="id_password">密码:</label></th><td>
<input type="password" name="password" required id="password" />
</td></tr>
<tr><th><label for="id_email">电子邮箱:</label></th><td><input type="email" name="email" id="id_email" required maxlength="254" /></td></tr>
<tr><th><label for="id_memo">简介:</label></th><td><textarea name="memo" cols="40" id="id_memo" required rows="10">
</textarea></td></tr>
<tr><th><label for="id_user_type">用户类型:</label></th><td><select name="user_type" required id="id_user_type">
  <option value="" selected>---------</option>

  <option value="0">普通管理员</option>

  <option value="1">超级管理员</option>

</select></td></tr>
	</table>
	<input style='position:relative;top:120px;left:20%;height:30px;width:200px' type='submit' onclick="document.getElementById('id_password').value=md5(document.getElementById('id_password').value)"  value='提交'/></br><span type='submit' style='position:relative;left:33%;top:125px'>{{status}}</span>
	</br>
	</br>
</form>
<img style='position:fixed;right:10%;top:150px' src='/static/img/zhuce-1.jpg'/>
</div>

<div style="position:fixed;bottom:0;left:40%">

	<h5>©华熙现场科技有限公司    <span style="color:black">版权所有</span> <a href="http://www.miitbeian.gov.cn"><span style="color:black">京ICP备16047864号-1</span></a ></h5>

</div>


</body>
</html>

monitor/templates/triggers.html
{% extends "master/layout.html" %}
{% load oldboy %}
{% block content %}

<h2 style='position:relative;left:3%'>主机触发器</h2>
	<form action='/ad/monitor/triggers/' method='POST'>{% csrf_token %}
		<table style='position:relative;left:8%;top:10px;bottom:50px' border='1'>
			<th>
				<td>模板名</td>
				<td>描述</td>
				<td></td>
			</th>		
			{% for item in data%}
			
			
			<tr name="RuleIndextable">
				<td>{{item.id}}</td>
				<td >{{item.name}}</td>
				<td>{{item.memo}}</td>
				<td style='border-style:none'><input id={{item.id}} type="button" value="保存"/></td>
			</tr>		
			{% endfor %}
			
			<tr name="new_triggers">
				<td></td>
				<td><input name="triggers_name" style="height:16px"/></td>
				<td><input name="triggers_memo" style="height:16px"/></td>
				<td style='border-style:none'><input type='submit' value='新增'/></td>
			</tr>
		
		</table>
	</form>
	<form><table style='position:relative;left:15%;top:20px;bottom:50px' border="1px">
	<tr ><div >
			<td><a href="/ad/monitor/triggers/{{up_page}}/">上一页</a></td>
			<td>&nbsp;<span>{{page_num}}</span>&nbsp;</td>
			<td><a href="/ad/monitor/triggers/{{down_page}}/">下一页</a></td>
		</div></tr>
	</table></form>
<img style="position:fixed;right:150px;bottom:134px;height:34px;width:34px" src="/static/img/sanjiaoxing2.png" />
<button id="backtop" style="position:fixed;right:150px;bottom:100px;height:34px;width:34px">Top</button>
<script type="text/javascript" src="/static/js/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
var jishi=document.getElementsByClassName("td-1");
			//遍历数组，给每个td添加点击事件
			for(var j=0;j<jishi.length;j++){
				jishi[j].onclick=function(){
				//首先要创造个输入框
				var shuru=document.createElement("input");
				//给输入框添加类型，因为输入框有很多的类型
				shuru.type="text";
				//输入框的内容是本身就有的，获取它的内容，用指针来代替
				shuru.value=this.innerText;
				var shuru1=shuru.value
				//把td的内容清空，然后把新建的节点加给它
				this.innerHTML="";
				this.appendChild(shuru);
				shuru.onblur=function(){
					shuru.parentNode.innerHTML=shuru.value;
				}
				shuru.focus();
				}
			}
backtop.onclick = function(){
	document.body.scrollTop = document.documentElement.scrollTop = 0;
}

</script>
{% endblock %}